services:
  ros:
    image: registry.robotics-lab.ru/robomarvel:v6
    build: .
    platform: linux/arm64
    container_name: ros
    privileged: true
    restart: always
    entrypoint: ["/src/entrypoint.sh"]
    ulimits:
      core: 0
    ports:
      - 8765:8765      # Foxglove Websocket
      - 8080:8080      # Jupyter Lab
      - 8889:8889      # MediaMTX HTTP
      - 8189:8189/udp  # MediaMTX WebRTC
    volumes:
      - ".:/src"
      - "/dev:/dev"
      - "/run/udev:/run/udev:ro"
      - "/usr/hobot:/usr/hobot:ro"
