; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 921600
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_filters = esp32_exception_decoder

build_src_filter = -<*> +<main.cpp> +<ESP32HWEncoderFix.cpp>
extra_scripts = pre:srcfilter.py
build_flags = -D ICM_20948_USE_DMP
lib_deps =
    https://github.com/sparkfun/SparkFun_ICM-20948_ArduinoLibrary.git
    sparkfun/SparkFun VL53L5CX Arduino Library
    simplefoc/SimpleDCMotor@^1.0.3
    simplefoc/SimpleFOCDrivers@^1.0.9
    fastled/FastLED@^3.10.3
    olikraus/U8g2@^2.36.18
    adafruit/Adafruit INA219@^1.2.3
    mathertel/OneButton
    hideakitai/Packetizer
